# Generated by Django 3.0.6 on 2020-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo_main', models.ImageField(upload_to='')),
                ('photo_1', models.ImageField(blank=True, upload_to='')),
                ('photo_2', models.ImageField(blank=True, upload_to='')),
                ('photo_3', models.ImageField(blank=True, upload_to='')),
                ('photo_4', models.ImageField(blank=True, upload_to='')),
                ('photo_5', models.ImageField(blank=True, upload_to='')),
                ('photo_6', models.ImageField(blank=True, upload_to='')),
                ('photo_7', models.ImageField(blank=True, upload_to='')),
                ('photo_8', models.ImageField(blank=True, upload_to='')),
                ('photo_9', models.ImageField(blank=True, upload_to='')),
                ('Accueil', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
